name: example-environment
channels:
  - conda-forge
dependencies:
  - octave_kernel
  - python=3.9.16
  - nipype
  - numpy
  - nilearn
  - scipy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
